### ISSUE TITLE
New File

### ISSUE THREAD

**Issue by brian-silverman** [scottsilverlabs/raspberrystem-ide#48] opened 2014-12-16 17:22 UTC
When clicking on "New File" in the Select File dialog, instead of staying in the dialog, immediately open that new file and close the dialog.

**Comment by Slowki** [comment] 2015-01-20 07:33
Caused by left over loading window debugging code, fixed by 7d5e5af424aadaaaf896de7cb063c1a6d42f2d11

**Closed by Slowki** 2015-01-20 07:33 UTC
Labels: high
